dependencies:
  - python=3.9
  - jupyter
  - numpy
  - pandas
  - matplotlib
  - tskit
  - gcc_linux-64
  - gxx_linux-64
  - make
  - gsl
  - cmake          # ← مهم جدًا لبناء SLiM
  - eigen         # ← مطلوب لـ SLiM
  - git           # ← إذا كنت تستنسخ من GitHub
